
<!DOCTYPE html>
<html>
<head>
	<title></title>
	
	
</head>
<body>
 <center><h1>ARYAN THAKUR</h1>
<header>
	<div class="container center-div shadow ">
	<div class="heading text-center mb-5 text-uppercase text-white"> ADMIN LOGIN PAGE </div>
	<div class="container row d-flex flex-row justify-content-center mb-5">
	<div class="admin-form shadow p-2 ">
	<form action="logincheck.php" method="POST">
	<div class="form-group">
	<label>Email ID</label>
	<input type="text" name="user" value="" class="form-control" autocomplete="off">
	</div>

    <div class="form-group">
	<label>Password</label>
	<input type="text" name="pass" value="" class="form-control" autocomplete="off">
	</div>
	
	</form>
	</div>
	</div>
	</div>
	<a href="16 2.php"><button>LOGIN</button></a>
</header>

</body>
</html>